SAMPLES: 
  A: genomes/AA010_contigs.fa
  B: genomes/AS011_contigs.fa
  C: genomes/AS013_contigs.fa
  D: genomes/AS031_contigs.fa
  E: genomes/AS083_contigs.fa
  F: genomes/AS085_contigs.fa
  G: genomes/AS091_contigs.fa
  H: genomes/AS093_contigs.fa
  I: genomes/AS096_contigs.fa
  J: genomes/AS113_contigs.fa
  K: genomes/AS116_contigs.fa
  L: genomes/AS124_contigs.fa
  M: genomes/AS126_contigs.fa

  