name: test pipeline

on: [push]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: ['3.10']
    steps: 
      - name: Set up python3
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
          
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Test workflow
        uses: ezherman/snakemake-github-action@5027c0e706ada924ab91e0501bd92185fc98de3c
        with: 
          directory: '.'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda'
          stagein: 'conda config --set channel_priority flexible'
