name: GitHub Actions Demo
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Set strict channel priority and update conda
      - name: Update Conda and configure channels
        run: |
          conda config --set channel_priority strict
          conda config --add channels defaults
          conda config --add channels conda-forge  # Ensures conda-forge is prioritized
          conda config --ad channels bioconda 

      - name: Testing
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --use-conda --configfile config/config.yaml'
          show-disk-usage-on-error: true
           
